name: tacs
channels:
  - conda-forge
  - defaults
dependencies:
  - cython>=0.29
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-libwinpthread-git
  - numpy
  - pip
  - python==3.8
  - scipy>=1.2.1
  - setuptools>=45.0
  - wheel
  - pip:
    - mpi4py>=3.0.2
    - pynastran>=1.3.3
